Inverse Grim Trigger

Why 0.965 discount only ecological info - cooperation locally stable, but not classified as such.


In [3]:
from imports import *
from information_conditions import Information_Conditions
from base_ecopg import *
from helper_functions import *
from simulation_and_results_functions import *

In [3]:
np.set_printoptions(precision=3, suppress=True, linewidth=200)


In [4]:
def add_degraded_state_policies_complete_info(strategy):
        
        strategy_propserous_and_degraded_state = strategy.copy()

        for i in [0, 2, 4, 6]:
            x = np.random.rand()
            strategy_propserous_and_degraded_state.insert(i, x)
        
        return strategy_propserous_and_degraded_state


def add_degraded_state_policies_ecological_info(strategy):
        
        strategy_propserous_and_degraded_state = strategy.copy()
        x = np.random.rand()
        strategy_propserous_and_degraded_state.insert(0, x)
        
        return strategy_propserous_and_degraded_state



In [7]:
def create_policy_from_strategy(agent_1_strategy, agent_2_strategy):


    agent_1_strategy = [[x, 1-x] for x in agent_1_strategy]
    agent_2_strategy = [[x, 1-x] for x in agent_2_strategy]

    policy = np.array([agent_1_strategy, agent_2_strategy])

    return policy


def epsilon_noise_for_strategy(determinstic_strategy, epsilon):
    #to avoid pure determinstic strategies, we remove e from 0  
    strategy_with_epsilon = [x + epsilon if x == 0 else x - epsilon if x == 1 else x for x in determinstic_strategy]
    return strategy_with_epsilon



def create_policy_with_noise_from_deterministic_strategy(agent_1_strategy, agent_2_strategy, epsilon):

    
    determinstic_policy = create_policy_from_strategy(agent_1_strategy, agent_2_strategy)
    
    
    agent_1_strategy_with_noise = epsilon_noise_for_strategy(agent_1_strategy, epsilon)
    agent_2_strategy_with_noise = epsilon_noise_for_strategy(agent_2_strategy, epsilon)

    noisy_policy = create_policy_from_strategy(agent_1_strategy_with_noise, agent_2_strategy_with_noise)

    return noisy_policy, determinstic_policy


In [6]:
strat = [0, 0, 0, 1]
strat = add_degraded_state_policies_complete_info(strat)
policy = create_policy_from_strategy(strat, strat)
mae = create_mae_ecopg_for_given_mode_POstratAC_expanded(mode = 'complete', discount_factor=0.99)
print(np.round(mae.Ps(policy),3))
# print(mae.obsdist(policy))

print(mae.env.Oset[0])


[0.029 0.005 0.055 0.    0.055 0.    0.851 0.005]
['c,c,g|', 'c,c,p|', 'c,d,g|', 'c,d,p|', 'd,c,g|', 'd,c,p|', 'd,d,g|', 'd,d,p|']


In [7]:
print(mae.id())

Information_ConditionsEcologicalPublicGood_2_1.2_5_-6_0.02_1e-04_NoDegChoi_h(1, 1, 1)__jPOstratAC_PartObs_[0.05 0.05]_[0.99 0.99]_[1 1]preFalse


In [ ]:
np.array([[0.9993087649345398], [0.9994180202484131]]

In [ ]:
strat_1 = [0.999087649345398]
strat_2 = [0.9994180202484131]
strat_1 = add_degraded_state_policies_ecological_info(strat_1)
strat_2 = add_degraded_state_policies_ecological_info(strat_2)

policy = create_policy_from_strategy(strat_1, strat_2)

print(policy)

mae_ecopg = create_mae_ecopg_for_given_mode_POstratAC_expanded(mode = 'ecological', discount_factor=0.965, m = -6.5)
print(np.round(mae_ecopg.obsdist(policy),3))
# print(mae.obsdist(policy))






[[[2.18087694e-01 7.81912306e-01]
  [9.99308765e-01 6.91235065e-04]]

 [[3.46622131e-01 6.53377869e-01]
  [9.99418020e-01 5.81979752e-04]]]
[[0.11300001 0.887     ]
 [0.11300001 0.887     ]]


In [42]:
strat_1 = [0.999]
strat_2 = [0.999]
strat_1 = add_degraded_state_policies_ecological_info(strat_1)
strat_2 = add_degraded_state_policies_ecological_info(strat_2)

policy = create_policy_from_strategy(strat_1, strat_2)

print("policy:", policy)

mae_ecopg = create_mae_ecopg_for_given_mode_POstratAC_expanded(mode = 'ecological', discount_factor=0.985, m = -6.5)
print("obsdist:", np.round(mae_ecopg.obsdist(policy),3))
print("Ps:", np.round(mae_ecopg.Ps(policy),3))
# print(mae.obsdist(policy))






policy: [[[0.2036967  0.7963033 ]
  [0.999      0.001     ]]

 [[0.36422117 0.63577883]
  [0.999      0.001     ]]]
obsdist: [[0.16600001 0.83400005]
 [0.16600001 0.83400005]]
Ps: [0.012      0.832      0.021      0.001      0.048      0.001
 0.08400001 0.        ]
