In [68]:
from imports import *
from information_conditions import Information_Conditions
from base_ecopg import *
from helper_functions import *
from simulation_and_results_functions import *

In [69]:
np.set_printoptions(precision=4, suppress=True, linewidth=200)


In [70]:
def add_degraded_state_policies_both_state_and_action(strategy):
        
        strategy_propserous_and_degraded_state = strategy.copy()

        for i in [0, 2, 4, 6]:
            x = np.random.rand()
            strategy_propserous_and_degraded_state.insert(i, x)
        
        return strategy_propserous_and_degraded_state


def add_degraded_state_policies_only_state(strategy):
        
        strategy_propserous_and_degraded_state = strategy.copy()
        x = np.random.rand()
        strategy_propserous_and_degraded_state.insert(0, x)
        
        return strategy_propserous_and_degraded_state



In [71]:
def create_policy_from_strategy(agent_1_strategy, agent_2_strategy):


    agent_1_strategy = [[x, 1-x] for x in agent_1_strategy]
    agent_2_strategy = [[x, 1-x] for x in agent_2_strategy]

    policy = np.array([agent_1_strategy, agent_2_strategy])

    return policy

In [72]:
def calculate_avg_value_given_policy_obs(policy, mode):

    mae_ecopg =  create_mae_ecopg_for_given_mode_POstratAC(mode)
    # mae_ecopg.has_last_statdist = False
    # mae_ecopg._last_statedist = None

    Vio = mae_ecopg.Vio(policy)
    obsdist = mae_ecopg.obsdist(policy)

    # print(Vio, "Vio")
    # print(obsdist, "obsdist")

    if mode == 'complete' or mode == 'ecological':
        Vio = Vio[:,1::2]
        obsdist = obsdist[:,1::2]
        obsdist = obsdist/obsdist.sum(axis = 1)

    agents = 0
    states = 1
    avg_value_agent_1, avg_value_agent_2 = jnp.einsum(Vio, [agents, states], obsdist , [agents, states], [agents])
    # print(avg_value_agent_1, avg_value_agent_2, "value of agents")

    return avg_value_agent_1, avg_value_agent_2

In [73]:
def calculate_avg_value_given_policy_state_mae_ecopg(policy, mode):

    mae_ecopg =  create_mae_ecopg_for_given_mode_POstratAC(mode)
    Vis = mae_ecopg.Vis(policy)
    mae_ecopg.has_last_statdist = False
    mae_ecopg._last_statedist = None
    state_dist = mae_ecopg._numpyPs(policy)

    
    E = 0.01
    state_dist = np.where(state_dist == 0, E, state_dist)

    if mode == 'complete' or mode == 'ecological':
        Vis = Vis[:,1::2]
        state_dist = state_dist[1::2]

    state_dist = state_dist/np.sum(state_dist)

    # print(Vis, "vis")
    # print(state_dist, "state dist")

    agents = 0
    states = 1
    avg_value_agent_1, avg_value_agent_2 = jnp.einsum(Vis, [agents, states], state_dist , [states], [agents])
    # print(avg_value_agent_1, avg_value_agent_2, "value of agents")

    return avg_value_agent_1, avg_value_agent_2



def calculate_avg_value_given_policy_state_test(policy, mode, mae):

    Vis = mae.Vis(policy)
    state_dist = mae.Ps(policy)

    # print(Vis, "vis")
    # print(state_dist, "state dist")
    
    if mode == 'complete' or mode == 'ecological':
        Vis = Vis[:,1::2]
        state_dist = state_dist[1::2]
        state_dist = state_dist/np.sum(state_dist)
    agents = 0
    states = 1
    avg_value_agent_1, avg_value_agent_2 = jnp.einsum(Vis, [agents, states], state_dist , [states], [agents])


    return  avg_value_agent_1, avg_value_agent_2



In [74]:
def metagame_reward_matrix_obs_ecopg(strategy_set_p1, strategy_set_p2, mode):
    p1_reward_matrix = np.zeros((len(strategy_set_p1), len(strategy_set_p2)))
    p2_reward_matrix = np.zeros((len(strategy_set_p1), len(strategy_set_p2)))

    for i, p1_strategy in enumerate(strategy_set_p1.values()):
        for j, p2_strategy in enumerate(strategy_set_p2.values()):

    
            policy = create_policy_from_strategy(p1_strategy, p2_strategy)
            value_p1, value_p2 = calculate_avg_value_given_policy_obs(policy, mode)
            p1_reward_matrix[i,j] = value_p1
            p2_reward_matrix[i,j] = value_p2

    return p1_reward_matrix, p2_reward_matrix



def metagame_reward_matrix_state_ecopg(strategy_set_p1, strategy_set_p2, mode):
    '''Vi estimate using vis and Ps instead of Vio and obsdist'''
    p1_reward_matrix = np.zeros((len(strategy_set_p1), len(strategy_set_p2)))
    p2_reward_matrix = np.zeros((len(strategy_set_p1), len(strategy_set_p2)))

    for i, p1_strategy in enumerate(strategy_set_p1.values()):
        for j, p2_strategy in enumerate(strategy_set_p2.values()):

            # print(p1_strategy, p2_strategy, "strat p1, p2")

            policy = create_policy_from_strategy(p1_strategy, p2_strategy)
            value_p1, value_p2 = calculate_avg_value_given_policy_state_mae_ecopg(policy, mode)

            # print(value_p1, value_p2 ,"value p1, p2")
            p1_reward_matrix[i,j] = value_p1
            p2_reward_matrix[i,j] = value_p2

    return p1_reward_matrix, p2_reward_matrix



def metagame_reward_matrix_state_test(strategy_set_p1, strategy_set_p2, mode, mae):
    '''Vi estimate using vis and Ps instead of Vio and obsdist'''
    p1_reward_matrix = np.zeros((len(strategy_set_p1), len(strategy_set_p2)))
    p2_reward_matrix = np.zeros((len(strategy_set_p1), len(strategy_set_p2)))

    for i, p1_strategy in enumerate(strategy_set_p1.values()):
        for j, p2_strategy in enumerate(strategy_set_p2.values()):

            # print(p1_strategy, p2_strategy, "strat p1, p2")


            policy = create_policy_from_strategy(p1_strategy, p2_strategy)
            value_p1, value_p2 = calculate_avg_value_given_policy_state_test(policy, mode, mae)

            p1_reward_matrix[i,j] = value_p1
            p2_reward_matrix[i,j] = value_p2

    return p1_reward_matrix, p2_reward_matrix


In [75]:
def create_determinstic_strategies_set_for_both_players(mode):
    '''creates deterministic strategy sets for given mode '''

    # E = 0.05
    mae_ecopg_for_evaluating_no_of_states = create_mae_ecopg_for_given_mode_POstratAC(mode)
    number_of_states = mae_ecopg_for_evaluating_no_of_states.Q
    
    if mode == 'none' or mode == 'social':
        determinstic_strategy_itertools = itertools.product([1 , 0], repeat = number_of_states)
        determinisic_strategy_lists = list(list(strat) for strat in determinstic_strategy_itertools)
        all_determinstic_strategy_dictionary_full = {str(strat):strat for strat in determinisic_strategy_lists}

    else:
        number_of_prosperous_states = int(number_of_states/2)
        determinstic_strategy_itertools = itertools.product([1, 0], repeat = number_of_prosperous_states)
        determinisic_strategy_lists = list(list(strat) for strat in determinstic_strategy_itertools)
        all_determinstic_strategy_dictionary_only_prosperous = {str(strat):strat for strat in determinisic_strategy_lists}

        if mode == 'complete':
             all_determinstic_strategy_dictionary_full = {key: add_degraded_state_policies_both_state_and_action(value) for key, value in all_determinstic_strategy_dictionary_only_prosperous.items()}
        elif mode == 'ecological':
             all_determinstic_strategy_dictionary_full = {key: add_degraded_state_policies_only_state(value) for key, value in all_determinstic_strategy_dictionary_only_prosperous.items()}


    strategy_set_p1 = all_determinstic_strategy_dictionary_full
    strategy_set_p2 = all_determinstic_strategy_dictionary_full

    return strategy_set_p1, strategy_set_p2

In [76]:
def reward_matrix_to_excel(p1_reward_matrix, p2_reward_matrix, strategy_set_p1, strategy_set_p2):

    '''p1 rewards pg 1. p2 rewards pg 2. rows -> p1 strategies, cols -> p2 strategies in both cases '''
    p1_reward_matrix = pd.DataFrame(p1_reward_matrix, index = list(strategy_set_p1.keys()), columns= list(strategy_set_p2.keys()))
    p2_reward_matrix = pd.DataFrame(p2_reward_matrix, index = list(strategy_set_p1.keys()), columns= list(strategy_set_p2.keys()))

    with pd.ExcelWriter('reward_matrix_only_action_2.xlsx') as excel_file:
        p1_reward_matrix.to_excel(excel_file, sheet_name='p1', index=True, header=True)
        p2_reward_matrix.to_excel(excel_file, sheet_name='p2', index=True, header=True)

In [77]:
def calculate_pure_strategy_nash_equilibria(payoffs_row, payoffs_col):
    game = pygambit.Game.from_arrays(payoffs_row, payoffs_col)
    result = pygambit.nash.enumpure_solve(game)
    return result.equilibria

In [78]:
def process_and_print_nash_equilibria_results(nash_equlibria_result, strategy_set_p1, strategy_set_p2):

    number_of_nash_equilbria = len(nash_equlibria_result)
    print("Total number of Nash ", number_of_nash_equilbria)

    '''better readable format of the strategies'''
    strategies_p1_array = np.array(list(strategy_set_p1.keys())) #just the list of strategies
    strategies_p2_array = np.array(list(strategy_set_p2.keys()))

    for eq in nash_equlibria_result:                       # each equilibrium profile
        strategy_profile_of_each_agent = [[float(p) for _, p in m] for r, m in eq.mixed_strategies()]    #converting mixed strategis to float

        p1_active_strategy = np.array(strategy_profile_of_each_agent[0]).astype(bool) #boolean conversion - for strategy in pure nash probability =  1, for strategy not in pure nash, probability = 0
        p2_active_strategy = np.array(strategy_profile_of_each_agent[1]).astype(bool)
        # float_profile = np.array() # iterate over (strategy, prob

        p1_nash_strategy = strategies_p1_array[p1_active_strategy]
        p2_nash_strategy =  strategies_p2_array[p2_active_strategy]

        
        print('P1:' , p1_nash_strategy)   #will only print the strategy found in nash
        print('P2:' , p2_nash_strategy)

        print('------')


'''


strategy_set_p1_only_action_array = np.array(list(strategy_set_p1_only_action.keys()))
strategy_set_p2_only_action_array = np.array(list(strategy_set_p2_only_action.keys()))

print(strategy_set_p1_only_action_array)

for eq in result.equilibria:                       # each equilibrium profile
    strategy_profile_of_each_agent = [[float(p) for _, p in m] for r, m in eq.mixed_strategies()]

    p1_active_strategy = np.array(strategy_profile_of_each_agent[0]).astype(bool)
    p2_active_strategy = np.array(strategy_profile_of_each_agent[1]).astype(bool)
    # float_profile = np.array() # iterate over (strategy, prob

    print('P1:' , strategy_set_p1_only_action_array[p1_active_strategy])
    print('P2:' , strategy_set_p2_only_action_array[p2_active_strategy])

    print('------')




'''

"\n\n\nstrategy_set_p1_only_action_array = np.array(list(strategy_set_p1_only_action.keys()))\nstrategy_set_p2_only_action_array = np.array(list(strategy_set_p2_only_action.keys()))\n\nprint(strategy_set_p1_only_action_array)\n\nfor eq in result.equilibria:                       # each equilibrium profile\n    strategy_profile_of_each_agent = [[float(p) for _, p in m] for r, m in eq.mixed_strategies()]\n\n    p1_active_strategy = np.array(strategy_profile_of_each_agent[0]).astype(bool)\n    p2_active_strategy = np.array(strategy_profile_of_each_agent[1]).astype(bool)\n    # float_profile = np.array() # iterate over (strategy, prob\n\n    print('P1:' , strategy_set_p1_only_action_array[p1_active_strategy])\n    print('P2:' , strategy_set_p2_only_action_array[p2_active_strategy])\n\n    print('------')\n\n\n\n\n"

In [79]:
def get_pure_nash_equilibria_all_deterministic_strategies_mode(mode):
    strategy_set_p1, strategy_set_p2 = create_determinstic_strategies_set_for_both_players(mode)
    p1_reward_matrix, p2_reward_matrix = metagame_reward_matrix_state_ecopg(strategy_set_p1, strategy_set_p2, mode)
    # p1_reward_matrix, p2_reward_matrix = metagame_reward_matrix_obs_ecopg(strategy_set_p1, strategy_set_p2, mode)

    print("p1: \n", p1_reward_matrix, "\n p2: \n", p2_reward_matrix)
    
    nash_equlibrium_result = calculate_pure_strategy_nash_equilibria(p1_reward_matrix, p2_reward_matrix)
    process_and_print_nash_equilibria_results(nash_equlibrium_result, strategy_set_p1, strategy_set_p2)

In [80]:
get_pure_nash_equilibria_all_deterministic_strategies_mode('none')

p1: 
 [[  36.9797 -294.3654]
 [-287.3218 -294.3871]] 
 p2: 
 [[  36.9797 -287.3218]
 [-294.3654 -294.3871]]
Total number of Nash  1
P1: ['[1]']
P2: ['[1]']
------


In [81]:
def check_policy_for_stability_Q_values(policy, mode):
    #works only for determentsic strtagues
    mae = create_mae_ecopg_for_given_mode_POstratAC('none')
    Qioa = mae.Qioa(policy)

In [82]:
mae = create_mae_ecopg_for_given_mode_POstratAC('none')
E = 0.0
policy = create_policy_from_strategy([1], [1])
Qioa = mae.Qioa(policy)

reverse_policy = 1 - policy

print(Qioa)
print(policy)
Vio = mae.Vio(policy)
# print(Qioa)

obsdist = mae.obsdist(policy)

# Qioa_2 =  np.random.randint(low = 0, high = 2, size = Qioa.shape)
# print(Qioa_2, "Qioa_2")
# obsdist_2 = np.random.randint(low = 0, high = 2, size = obsdist.shape)
# print(obsdist_2, "obsdist_2")
# print(obsdist)

agents = 0
actions = 1
states = 2

Qi = jnp.einsum(Qioa, [agents, states, actions],  policy, [agents, states, actions], [agents])  #Here, we're calculating the average Q value for each agent - across the policy and obsdist
print("Qi", Qi)

Qi_reverse = jnp.einsum(Qioa, [agents, states, actions],  reverse_policy, [agents, states, actions], [agents])  #Here, we're calculating the average Q value for each agent - across the policy and obsdist
print("Qi_reverse", Qi_reverse)

# avg_value_agent_1, avg_value_agent_2 = jnp.einsum(Vio, [agents, states], obsdist , [agents, states], [agents])
# print(avg_value_agent_1, avg_value_agent_2, "value of agents")


np.all(Qi < Qi_reverse)
# print(Qioa[0,:,:])

[[[50.   51.91]]

 [[50.   51.91]]]
[[[1 0]]

 [[1 0]]]
Qi [50. 50.]
Qi_reverse [51.91 51.91]


Array(True, dtype=bool)

#strategy vs actions

WSLS - [1, 0, 0, 1] 
Q_ioa for each. 

0.999

value functions -> policy (Q and SA)
policy -> actor critic


actor critic also uses Q values

In [ ]:
def create_determinstic_strategies_set_for_both_players_with_epsilon(mode):
    '''creates deterministic strategy sets for given mode '''

    E = 0.01
    mae_ecopg_for_evaluating_no_of_states = create_mae_ecopg_for_given_mode_POstratAC(mode)
    number_of_states = mae_ecopg_for_evaluating_no_of_states.Q
    
    if mode == 'none' or mode == 'social':
        determinstic_strategy_itertools = itertools.product([1 - E , 0 + E], repeat = number_of_states)
        determinisic_strategy_lists = list(list(strat) for strat in determinstic_strategy_itertools)
        all_determinstic_strategy_dictionary_full = {str(strat):strat for strat in determinisic_strategy_lists}

    else:
        number_of_prosperous_states = int(number_of_states/2)
        determinstic_strategy_itertools = itertools.product([1 - E , 0 + E], repeat = number_of_prosperous_states)
        determinisic_strategy_lists = list(list(strat) for strat in determinstic_strategy_itertools)
        all_determinstic_strategy_dictionary_only_prosperous = {str(strat):strat for strat in determinisic_strategy_lists}

        if mode == 'complete':
             all_determinstic_strategy_dictionary_full = {key: add_degraded_state_policies_both_state_and_action(value) for key, value in all_determinstic_strategy_dictionary_only_prosperous.items()}
        elif mode == 'ecological':
             all_determinstic_strategy_dictionary_full = {key: add_degraded_state_policies_only_state(value) for key, value in all_determinstic_strategy_dictionary_only_prosperous.items()}


    strategy_set_p1 = all_determinstic_strategy_dictionary_full
    strategy_set_p2 = all_determinstic_strategy_dictionary_full

    return strategy_set_p1, strategy_set_p2




def process_and_print_nash_equilibria_results_test(nash_equlibria_result, strategy_set_p1, strategy_set_p2, mode, mae):

    number_of_nash_equilbria = len(nash_equlibria_result)
    print("Total number of Nash ", number_of_nash_equilbria)

    '''better readable format of the strategies'''
    strategies_p1_array = np.array(list(strategy_set_p1.values())) #just the list of strategies
    strategies_p2_array = np.array(list(strategy_set_p2.values()))

    for eq in nash_equlibria_result:                       # each equilibrium profile
        strategy_profile_of_each_agent = [[float(p) for _, p in m] for r, m in eq.mixed_strategies()]    #converting mixed strategis to float

        p1_active_strategy = np.array(strategy_profile_of_each_agent[0]).astype(bool) #boolean conversion - for strategy in pure nash probability =  1, for strategy not in pure nash, probability = 0
        p2_active_strategy = np.array(strategy_profile_of_each_agent[1]).astype(bool)
        # float_profile = np.array() # iterate over (strategy, prob

        p1_nash_strategy = (strategies_p1_array[p1_active_strategy])[0]
        p2_nash_strategy =  (strategies_p2_array[p2_active_strategy])[0]

        
        print('P1:' , p1_nash_strategy)   #will only print the strategy found in nash
        print('P2:' , p2_nash_strategy)

        policy_test = create_policy_from_strategy(p1_nash_strategy, p2_nash_strategy)

        print(calculate_avg_value_given_policy_state_test_with_print(policy_test, mode, mae))

        print('------')


def calculate_avg_value_given_policy_state_test_with_print(policy, mode, mae):

    Vis = mae.Vis(policy)
    state_dist = mae.Ps(policy)

    print(Vis, "vis")
    print(state_dist, "state dist")
    
    if mode == 'complete' or mode == 'ecological':
        Vis = Vis[:,1::2]
        state_dist = state_dist[1::2]
        state_dist = state_dist/np.sum(state_dist)
    agents = 0
    states = 1
    avg_value_agent_1, avg_value_agent_2 = jnp.einsum(Vis, [agents, states], state_dist , [states], [agents])

    print(avg_value_agent_1, avg_value_agent_2, "Vi")

    return  avg_value_agent_1, avg_value_agent_2


'''Memo1pd testing for understanding '''



mode = 'social'

env_socdi = SocialDilemma(R=0.8, T=1, S=-0.5, P= 0)
env_memo1pd = HistoryEmbedded(env_socdi, h=(1,1,1))

strategy_set_p1, strategy_set_p2 = create_determinstic_strategies_set_for_both_players_with_epsilon(mode)


mae_socdi = stratAC(env=env_memo1pd, learning_rates=0.1, discount_factors= 0.99)

p1_reward_matrix_only_state, p2_reward_matrix_only_state = metagame_reward_matrix_state_test(strategy_set_p1, strategy_set_p2, mode,mae_socdi)

payoffs_row = p1_reward_matrix_only_state
payoffs_col  = p2_reward_matrix_only_state

game = pygambit.Game.from_arrays(payoffs_row, payoffs_col)


result = pygambit.nash.enumpure_solve(game)



process_and_print_nash_equilibria_results_test(result.equilibria, strategy_set_p1, strategy_set_p2, mode, mae_socdi)

In [105]:
'''Memo1pd testing for understanding '''



mode = 'social'

env_socdi = SocialDilemma(R=0.8, T=1, S=-0.5, P= 0)
env_memo1pd = HistoryEmbedded(env_socdi, h=(1,1,1))

strategy_set_p1, strategy_set_p2 = create_determinstic_strategies_set_for_both_players_with_epsilon(mode)


mae_socdi = stratAC(env=env_memo1pd, learning_rates=0.1, discount_factors= 0.99)

p1_reward_matrix_only_state, p2_reward_matrix_only_state = metagame_reward_matrix_state_test(strategy_set_p1, strategy_set_p2, mode,mae_socdi)

payoffs_row = p1_reward_matrix_only_state
payoffs_col  = p2_reward_matrix_only_state

game = pygambit.Game.from_arrays(payoffs_row, payoffs_col)


result = pygambit.nash.enumpure_solve(game)



process_and_print_nash_equilibria_results_test(result.equilibria, strategy_set_p1, strategy_set_p2, mode, mae_socdi)

Total number of Nash  3
P1: [0.99 0.01 0.01 0.99]
P2: [0.99 0.01 0.01 0.99]
[[77.3666 76.5826 76.5825 77.3665]
 [77.3666 76.5826 76.5825 77.3665]] vis
[0.9607 0.0099 0.0099 0.0195] state dist
77.35103 77.35103 Vi
(Array(77.351, dtype=float32), Array(77.351, dtype=float32))
------
P1: [0.99 0.01 0.01 0.01]
P2: [0.99 0.01 0.01 0.01]
[[27.0722  0.7635  0.7635  0.7635]
 [27.0722  0.7635  0.7635  0.7635]] vis
[0.005  0.0099 0.0099 0.9752] state dist
0.8950479 0.89504796 Vi
(Array(0.895, dtype=float32), Array(0.895, dtype=float32))
------
P1: [0.01 0.01 0.01 0.01]
P2: [0.01 0.01 0.01 0.01]
[[0.503 0.503 0.503 0.503]
 [0.503 0.503 0.503 0.503]] vis
[0.0001 0.0099 0.0099 0.9801] state dist
0.5030022 0.5030023 Vi
(Array(0.503, dtype=float32), Array(0.503, dtype=float32))
------


In [ ]:
def compute_avg_q_value(Qioa, obsdist, policy):

    

_IncompleteInputError: incomplete input (3447455901.py, line 3)